### ISSUE TITLE
How to load custom css and js paths

### ISSUE THREAD

**Issue by emilmahler** [Appsilon/shiny.semantic#109]
According to this closed issue (https://github.com/Appsilon/semantic.dashboard/issues/110) you can specify a custom css file. This is useful for me, as you can't point to the default cdn behind an https connection (this results in a cross domain violation). How is this done in practice, for the css and js files?

For example, if in my shiny app, I put semantic.min.css and semantic.min.js in the www folder (all content of which is visible to the browser), I hoped you could maybe do:
options(shiny.custom.semantic = 'www/')

This didn't work. Nor did this:
options(shiny.custom.semantic = 'https://example.com/public/')

where https://example.com/public/semantic.min.css and https://example.com/public/semantic.min.js exist. The first item in the cran documentation is CDN_PATH, but it doesn't state how to change this.

**Comment by dokato** [comment]
Hi, well... according to this piece of code it should work: https://github.com/Appsilon/shiny.semantic/blob/5aa1416ed50d933870ea5c885ff3780519fb6beb/R/semanticPage.R#L25
But if you say so, it embarrassingly doesn't. Let me check that.

BTW Have you checked the paths to your css and js components? Are they still taken from our CDN?

**Comment by dokato** [comment]
Hi @emilmahler, sorry to keep you waiting for so long. The problem was fixed in PR #119 . Indeed you noticed a pretty cheeky bug in our css/js control. Thanks for that!
I made the flow easier now by removing some options and fixing the documentation. Additionally, in `examples/customss` you have a quick demo on how to make it work. Hope it helps!
Feel free to reopen if needed.
