### ISSUE TITLE
calendar changes date according to browser time zone

### ISSUE THREAD

**Issue by jakubnowicki** [Appsilon/shiny.semantic#312]
When updating value of `calendar` input the date is converted to local browser time zone (with the date converted to datetime where time is set to midnight). If the time zone of the value is not provided, it assumes that it is "UTC", thus if the local time zone is "UTC-X", the date will be changed to the day before. As a result, the value returned by the input will be the day before, but without the time zone (it will use "UTC" as default). 

This behavior can be reproduced by changing your local computer time (tested on Windows).

Minimal example:

`shiny`: 1.5.0
`shiny.semantic`: 0.4.0

```
library(shiny)
library(shiny.semantic)

ui <- semanticPage(
    shiny.semantic::calendar(input_id = "semantic_calendar", type = "date"),
    shiny::dateInput(inputId = "shiny_calendar", label = NULL),
    action_button(input_id = "update_date", label = "Update date to 2010-10-19")
)

server <- function(input, output, session) {
    observeEvent(input$update_date, {
        date <- "2010-10-19"
        update_calendar(
            session,
            "semantic_calendar",
            value = date
        )

        updateDateInput(
            session,
            "shiny_calendar",
            value = date
        )
    })

    observe({
        req(input$shiny_calendar)
        print("Shiny calendar:")
        print(input$shiny_calendar)
        print(lubridate::tz(input$shiny_calendar))
    })

    observe({
        req(input$semantic_calendar)
        print("Semantic calendar:")
        print(input$semantic_calendar)
        print(lubridate::tz(input$semantic_calendar))
    })
}

shinyApp(ui = ui, server = server)
```

Output:
![image](https://user-images.githubusercontent.com/7279715/93746155-cf25ec00-fbdb-11ea-90bf-9dfcbc4b7903.png)

**Comment by rabiibouhestine** [comment]
This issue is caused by the fomantic function `calendar`, in fact the issue occurs only when the date is passed in the format yyyy-mm-dd, the other formats don't cause issues.


![calendardebug](https://user-images.githubusercontent.com/15175871/102330110-add56180-3f78-11eb-82c9-528361fd1a31.png)


This has been reported to fomantic before ([here](https://github.com/fomantic/Fomantic-UI/issues/935)) and actually this is caused by `new Date()`.


![Screenshot from 2020-12-16 23-52-07](https://user-images.githubusercontent.com/15175871/102332742-09551e80-3f7c-11eb-8f40-7bbf418e934c.png)


For now, I believe an easy solid fix is to just transform whatever is provided by the user to the format 'yyyy/mm/dd' before passing it to the js binding. @jakubnowicki @dokato
