### ISSUE TITLE
Masking shiny's inputs can cause problems

### ISSUE THREAD

**Issue by daattali** [Appsilon/shiny.semantic#328]
If you have `shiny.semantic` attached (if at any point in the past `library(shiny.semantic)` was ran), it will cause problems for any non-semantic shiny app.

For example, in the following simple shiny app, if `shiny.semantic` is loaded, the UI of the shiny app would look broken:

```
library(shiny)
ui <- fluidPage(
  textInput("test", "test", "hello")
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```

![image](https://user-images.githubusercontent.com/952340/102137191-6cce3780-3e28-11eb-915b-af3be9f5401f.png)

Some other inputs, such as selectInput, would cause bigger issues - the input wouldn't register with shiny (likely because the required javascript is missing).

I understand the initial reasoning for wanting to mask shiny's inputs, so that developers can simply swap out `fluidPage` for `semanticPage`. But it's generally not a good idea for a package to cause side effects on load, especially when these side effects can cause issues, and this is a good example of that. The inputs should only use the semantic version when they're used in a semantic app.

**Comment by dokato** [comment]
Hmmm... 🤔 I get your point here, but in general, I think that mixing the Bootstrap and Fomantic libraries is rather non-desired behaviour, and we try to be quite explicit with that. With what you said, it's lesser of a `shiny.semantic` issue, but rather namespace masking problem in R, isn't it? For example, if I load `purrr` and `maps` I can also encounter problems when calling `map`. Your example could be easily fixed by calling: `shiny::textInput("test", "test", "hello")`. I see what you mean, though.

Indeed, the idea was to make for the user an easy transition from stanard shiny UI elements. The camelcase syntax functions are merely wrappers for semantic equivalents written in snake case. Do you think that the latter would be enough then?

**Comment by daattali** [comment]
You're right, it is a problem that comes up in other packages too--and in every case that it comes up, it results in bugs for many people, `dplyr::lag` is a classic example :p

I don't have opinion on providing aliases to functions with different versions of spelling (well, I do, but that's very personal and subjective). But I think a potential solution could be to set some flag in `semanticPage()` and then in the masked functions if the flag is set then you use the semantic version and if not then call shiny's version. Maybe it wouldn't work, but worth exploring IMO

**Comment by daattali** [comment]
Another option I could suggest is to show a warning message if `fluidPage()` or other top-level UI funcitons are called. I think (might be wrong) that `fluidPage()` et al are not meant to be used when using shiny.semantic, and if that's the case then calling these functions could be an indication that shiny.semantic isn't being used so the user can be warned.

**Comment by dokato** [comment]
Thats actually a neat idea, I like it! Thanks, @daattali!

**Comment by dracodoc** [comment]
I'm also having problems running the main example code(examples/app.R) because of name masking problem.
- First I need to manually install all the packages used in code, including one `purrrlyr` call buried in the middle of code. I suggest to use `pacman::p_load` to load packages in example code which will also install the packages for user automatically, which will make much better user experience. And the `purrrlyr` package should be installed/loaded in beginning explicitly (at least require it).
- Then the main example code keep giving error, mostly by textinput/dateInput was actually using shiny version instead of semantic version. In the code shiny.semantic is loaded later than shiny, but somehow the error still happened.

Many users can be turned off now for not be able to run the example. (the individual examples are simpler and easier to run).

I think in future this same name function can cause more problems, because you have to load shiny package, and sometimes the environment can be complex and unpredictable things can happen.

I'll suggest to add a prefix/postfix to all same name functions. Something like `se.dateInput`. You can still swap to shiny version by simple text search/replace, but it will be explicit on which function is used. If there are same name functions, the different version should be complete compatible in interface and can fully replace the original version.

**Comment by esraay** [comment]
I tested this example and saw that the problem was already fixed.

`library(shiny)
library(shiny.semantic)
ui <- fluidPage(
  shiny::textInput("test", "test", "hello"),
  shiny.semantic::textInput("test", "test", "hello")
)
server <- function(input, output, session) {}
shinyApp(ui, server)`
